name: manage-azure-policy-648f67aa
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'exportedpolicy/policies/Configure_VM_EncryptionAtHost_85373c99-d641-4d7c-b5c3-221139844e64/**'
#      - .github/workflows/manage-azure-policy-648f67aa.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_648f67aa}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          exportedpolicy/policies/Configure_VM_EncryptionAtHost_85373c99-d641-4d7c-b5c3-221139844e64/**
